# Generated by Django 4.0.2 on 2022-02-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('time_published', models.DateTimeField(blank=True, verbose_name='Время публикации')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('minutes_to_read', models.DecimalField(blank=True, decimal_places=1, max_digits=3, verbose_name='Минут на прочтение')),
                ('quantity_words', models.IntegerField(blank=True, verbose_name='Количество слов')),
                ('image_link', models.CharField(blank=True, max_length=250, verbose_name='Ссылка на фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
        ),
    ]
